---
- name: Update, install Docker, and deploy the container
  hosts: vagrant
  become: yes
  vars:
    docker_image_name: "baselabouelnour/devops-odc-final-project:latest"
    container_name: "the-weather-app"

  tasks:
    # Step 1: Update the system and install Docker
    - name: Update the system
      shell: |
        apt-get update
        apt-get dist-upgrade -y

    - name: Install required packages for Docker
      shell: |
        apt-get install -y apt-transport-https ca-certificates curl software-properties-common

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

    - name: Install Docker
      shell: apt-get install -y docker-ce

    - name: Start and enable Docker service
      shell: |
        systemctl start docker
        systemctl enable docker

    # Step 2: Pull and run the Docker image
    - name: Pull Docker image from Docker Hub
      shell: docker pull {{ docker_image_name }}

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image_name }}"
        state: started
        restart_policy: always
        ports:
          - "5000:5000"

