apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app
  labels:
    tier: app

spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        tier: app
    spec:
      containers:
      - name: weather-app
        image: baselabouelnour/devops-odc-final-project